In [1]:
import pandas as pd
import numpy as np
import random

np.random.seed(42)
random.seed(42)

In [2]:
departments = [
    'Sales',
    'HR',
    'IT',
    'Finance',
    'Marketing',
    'Operations'
]

job_roles = {
    'Sales': ['Sales Executive', 'Sales Manager'],
    'HR': ['HR Executive', 'Recruiter'],
    'IT': ['Developer', 'Data Analyst', 'System Admin'],
    'Finance': ['Accountant', 'Financial Analyst'],
    'Marketing': ['Marketing Executive', 'SEO Specialist'],
    'Operations': ['Operations Executive', 'Operations Manager']
}

In [3]:
data = []

for i in range(1, 5001):

    department = random.choice(departments)

    role = random.choice(job_roles[department])

    age = np.random.randint(22, 60)

    gender = random.choice(['Male', 'Female'])

    years_at_company = np.random.randint(0, 20)

    overtime = random.choice(['Yes', 'No'])

    monthly_income = np.random.randint(25000, 150000)

    job_satisfaction = np.random.randint(1, 6)

    work_life_balance = np.random.randint(1, 6)

    training_hours = np.random.randint(5, 80)

    performance_rating = np.random.randint(1, 6)

    distance_from_home = np.random.randint(1, 40)

    # Attrition Logic
    attrition_score = 0

    if overtime == 'Yes':
        attrition_score += 3

    if job_satisfaction <= 2:
        attrition_score += 3

    if work_life_balance <= 2:
        attrition_score += 2

    if years_at_company < 2:
        attrition_score += 2

    if monthly_income < 40000:
        attrition_score += 2

    attrition_probability = min(attrition_score / 10, 0.9)

    attrition = np.random.choice(
        ['Yes', 'No'],
        p=[attrition_probability, 1 - attrition_probability]
    )

    data.append({
        'employee_id': f'EMP{i:05}',
        'age': age,
        'gender': gender,
        'department': department,
        'job_role': role,
        'monthly_income': monthly_income,
        'years_at_company': years_at_company,
        'overtime': overtime,
        'job_satisfaction': job_satisfaction,
        'work_life_balance': work_life_balance,
        'training_hours': training_hours,
        'performance_rating': performance_rating,
        'distance_from_home': distance_from_home,
        'attrition': attrition
    })

df = pd.DataFrame(data)

df.head()

,employee_id,age,gender,department,job_role,monthly_income,years_at_company,overtime,job_satisfaction,work_life_balance,training_hours,performance_rating,distance_from_home,attrition
0,EMP00001,50,Male,Operations,Operations Executive,144879,14,No,5,5,79,3,24,No
1,EMP00002,45,Male,HR,HR Executive,92221,2,Yes,5,2,34,2,21,No
2,EMP00003,43,Female,Operations,Operations Executive,118016,11,Yes,1,3,63,2,28,No
3,EMP00004,36,Male,Sales,Sales Executive,60773,14,Yes,3,4,59,4,3,No
4,EMP00005,28,Male,Marketing,Marketing Executive,105038,8,No,2,4,64,2,9,Yes

In [4]:
df.shape

(5000, 14)

In [5]:
# Add missing values intentionally

for col in ['monthly_income', 'job_satisfaction', 'work_life_balance']:

    idx = np.random.choice(df.index, 40, replace=False)

    df.loc[idx, col] = np.nan

In [6]:
duplicates = df.sample(20)

df = pd.concat([df, duplicates], ignore_index=True)

In [7]:
df.shape

(5020, 14)

In [9]:
df.to_csv('./data/hr_dataset.csv', index=False)

In [10]:
df.head()

,employee_id,age,gender,department,job_role,monthly_income,years_at_company,overtime,job_satisfaction,work_life_balance,training_hours,performance_rating,distance_from_home,attrition
0,EMP00001,50,Male,Operations,Operations Executive,144879.0,14,No,5.0,5.0,79,3,24,No
1,EMP00002,45,Male,HR,HR Executive,92221.0,2,Yes,5.0,2.0,34,2,21,No
2,EMP00003,43,Female,Operations,Operations Executive,118016.0,11,Yes,1.0,3.0,63,2,28,No
3,EMP00004,36,Male,Sales,Sales Executive,60773.0,14,Yes,3.0,4.0,59,4,3,No
4,EMP00005,28,Male,Marketing,Marketing Executive,105038.0,8,No,2.0,4.0,64,2,9,Yes

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5020 entries, 0 to 5019
Data columns (total 14 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   employee_id         5020 non-null   object
 1   age                 5020 non-null   int64
 2   gender              5020 non-null   object
 3   department          5020 non-null   object
 4   job_role            5020 non-null   object
 5   monthly_income      4979 non-null   float64
 6   years_at_company    5020 non-null   int64
 7   overtime            5020 non-null   object
 8   job_satisfaction    4978 non-null   float64
 9   work_life_balance   4980 non-null   float64
 10  training_hours      5020 non-null   int64
 11  performance_rating  5020 non-null   int64
 12  distance_from_home  5020 non-null   int64
 13  attrition           5020 non-null   object
dtypes: float64(3), int64(5), object(6)
memory usage: 549.2+ KB

In [12]:
df.describe()

,age,monthly_income,years_at_company,job_satisfaction,work_life_balance,training_hours,performance_rating,distance_from_home
count,5020.000000,4979.000000,5020.000000,4978.000000,4980.000000,5020.000000,5020.000000,5020.000000
mean,40.572311,87588.002410,9.491633,3.018883,3.026305,42.039044,3.028088,19.921315
std,10.855962,36369.706712,5.745874,1.415224,1.420841,21.616872,1.406092,11.257442
min,22.000000,25005.000000,0.000000,1.000000,1.000000,5.000000,1.000000,1.000000
25%,31.000000,55935.000000,5.000000,2.000000,2.000000,23.000000,2.000000,10.000000
50%,41.000000,87539.000000,9.000000,3.000000,3.000000,42.000000,3.000000,20.000000
75%,50.000000,118790.500000,14.000000,4.000000,4.000000,61.000000,4.000000,30.000000
max,59.000000,149983.000000,19.000000,5.000000,5.000000,79.000000,5.000000,39.000000

In [13]:
df.describe(include='object')

       employee_id  gender department    job_role overtime attrition
count         5020    5020       5020        5020     5020      5020
unique        5000       2          6          13        2         2
top       EMP03394  Female    Finance  Accountant      Yes        No
freq             2    2518        878         448     2536      3030

In [14]:
df.isnull().sum()

employee_id            0
age                    0
gender                 0
department             0
job_role               0
monthly_income        41
years_at_company       0
overtime               0
job_satisfaction      42
work_life_balance     40
training_hours         0
performance_rating     0
distance_from_home     0
attrition              0
dtype: int64

In [15]:
df.duplicated().sum()

20

In [16]:
df['monthly_income'].fillna(
    df['monthly_income'].median(),
    inplace=True
)

df['job_satisfaction'].fillna(
    df['job_satisfaction'].median(),
    inplace=True
)

df['work_life_balance'].fillna(
    df['work_life_balance'].median(),
    inplace=True
)

In [17]:
df.drop_duplicates(inplace=True)

In [18]:
df.isnull().sum()

employee_id           0
age                   0
gender                0
department            0
job_role              0
monthly_income        0
years_at_company      0
overtime              0
job_satisfaction      0
work_life_balance     0
training_hours        0
performance_rating    0
distance_from_home    0
attrition             0
dtype: int64

In [19]:
df.duplicated().sum()

0

In [20]:
df.to_csv('./data/cleaned_hr_dataset.csv', index=False)